#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
  path: /api/setup-check
  controller: App\Controller\DefaultController::setupCheck

exchange_rates:
  resource: '../src/App/Controller/ExchangeRateController.php'
  type: annotation

index:
  path: /{wildcard}
  defaults:
    _controller: App\Controller\DefaultController::index
  requirements:
    wildcard: .*
